export const FUNNY_NAMES = [
  'Gipsz Elek',
  'Bor Ivó',
  'Alka Ida',
  'Feles Elek',
  'Békés Csaba',
  'Har Mónika',
  'Ka Pál',
  'Git Áron',
  'Kasza Blanka',
  'Dil Emma',
  'Hot Elek',
  'Karam Ella',
  'Citad Ella',
  'Csin Csilla',
  'Bo Lívia',
  'Am Erika',
  'Bud Izsák',
  'Fejet Lenke',
  'Idét Lenke',
  'Hát Izsák',
  'Bevíz Elek',
  'Chat Elek',
  'Ének Elek',
  'Lev Elek',
  'Diz Elek',
  'Boro Zoltán',
  'Buz Imre',
  'Gec Imre',
  'Cicz Imre',
  'Füty Imre',
  'Ka Kata',
  'Ge Cili',
  'Ci Cili',
  'Di Dia',
  'Dia Dóra',
  'Kup Ica',
  'Kukor Ica',
  'Mangal Ica',
  'Gaz Ella',
  'Disz Nóra',
  'Külö Nóra',
  'Hú Zóra',
  'Gá Zóra',
  'Fin Gábor',
  'Kala Pál',
  'Bekre Pál',
  'Ceruza Elemér',
  'Lapos Elemér',
  'B. Elek',
  'B. Ödön',
  'Körm Ödön',
  'Fo Soma',
  'Ba Szonja',
  'Fa Szonja',
  'Major Anna',
  'Bármi Áron',
  'Lekv Áron',
  'Akcíós Áron',
  'Diszkont Áron',
  'Egriv Áron',
  'Ant Rax',
  'Aloe Vera',
  'Hó Fehérke',
  'Cserép Virág',
  'Gyöngy Virág',
  'Bugyi Virág',
  'Futó Rózsa',
  'Ke Rozi(n)',
  'Ke Feri',
  'Ka Kálmán',
  'Fi Kálmán',
  'Beka Kálmán',
  'Bekő Tóni',
  'Hokkan Tóni',
  'Krep Tomi',
  'Masz Tibi',
  'Fá Zoltán',
  'Bak Zoltán',
  'Hugyo Zoltán',
  'Fiká Zoltán',
  'Kan Béla',
  'Kó Laci',
  'Ma Laci',
  'Fity Matyi',
  'Hüvely Matyi',
  'Heppi Endre',
  'Happy Endre',
  'Csecs Emőke',
  'Bimbó Emil',
  'Heu Réka',
  'Hatá Sára',
  'Kapd Bea',
  'Légy Ottó',
  'Kér Ede',
  'Keres Ede',
  'Ebéd Elek',
  'Folyékony Szilárd',
  'Krokod Ilus',
  'Cicam Ica',
  'Harci Marci',
];

// Kever es visszaad n random nevet
export function getRandomNames(count: number): string[] {
  const shuffled = [...FUNNY_NAMES].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// Visszaad egy random nevet ami meg nincs hasznalva
export function getRandomUnusedName(usedNames: string[]): string {
  const available = FUNNY_NAMES.filter(name => !usedNames.includes(name));
  if (available.length === 0) {
    return `Jatekos ${usedNames.length + 1}`;
  }
  return available[Math.floor(Math.random() * available.length)];
}
